### ISSUE TITLE
minimap highlighting overrides main buffer highlighting on bd/bw

### ISSUE THREAD

**Issue by rabirabirara** [wfxr/minimap.vim#61]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/minimap.vim/blob/master/README.md) (especially F.A.Q section)
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [x] Windows
    - [ ] Others:

## Version info

Neovim 0.5.0, Vim 8.2

## Problem and steps to reproduce

First noted in https://github.com/wfxr/minimap.vim/issues/59#issuecomment-794044722.  The behavior of Vim and Neovim to date is that, when the minimap is wiped out with 'bwipeout' on `WinEnter <buffer>`, the buffer that is next entered takes on the minimap's highlight matches.  If you have a custom highlight set, this is especially jarring.

**Comment by rabirabirara** [comment]
Fixed in 92d86ce178e7d9afc6795fa89b0b6a575e9d9db2.

**Comment by wfxr** [comment]
I find this problem still exists in some scenerios. For example calling `:quit` command while there are unsaved modifications.
